language: elixir
sudo: false
elixir: 1.4.1
otp_release: 19.1
matrix:
  include:
    - elixir: 1.3.0
      otp_release: 18.1
notifications:
  recipients:
    - jonathan@veyond.io
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
